create table users (
    id uuid primary key,
    full_name varchar(64) not null,
    email varchar(64) not null,
	password varchar(64),
	phone_number varchar(64),
	nickname varchar(64) not null,
	bio varchar(64) not null,
	city varchar(64) not null,
	province varchar(64) not null,
	user_type varchar(64) not null,
	send_notifications boolean not null,
	moving_reason varchar(64),
	has_roommates boolean,
	has_security_deposit boolean,
	is_smoker boolean,
	has_prev_lawsuit boolean,
	has_prev_eviction boolean,
	can_credit_check boolean,
	has_pets boolean,
	additional_details varchar(64),
	move_in_date varchar(64),
	move_out_date varchar(64),
	property_management_company varchar(64),
	additional_details_lease varchar(64),
	monthly_budget_min numeric(10, 2) not null,
	monthly_budget_max numeric(10, 2) not null
);

