create table user (
    id uuid primary key,
    full_name varchar(64) not null,
    email varchar(64) not null,
	password varchar(64),
	phone_number varchar(64),
	nickname varchar(64) not null,
	bio varchar(64) not null,
	city varchar(64) not null,
	province varchar(64) not null,
	user_type varchar(64) not null,
	send_notifications boolean not null,
	moving_reason varchar(64),
	has_roommates boolean not null,
	has_security_deposit boolean not null,
	is_smoker boolean not null,
	has_prev_lawsuit boolean not null,
	has_prev_eviction boolean not null,
	can_credit_check boolean not null,
	has_pets boolean not null,
	additional_details varchar(64),
	move_in_date varchar(64),
	moveOutDate varchar(64),
	property_management_company varchar(64),
	additional_details_lease varchar(64),
	monthly_budget_min numeric(10, 9) not null,
	monthly_budget_max numeric(10, 9) not null,
);