create table users (
    id uuid primary key,
    full_name varchar(64),
    email varchar(64),
	password varchar(64),
	user_status varchar(64),
	last_updated varchar(64),
	created_on varchar(64),
	phone_number varchar(64),
	nickname varchar(64),
	bio varchar(64),
	user_type varchar(64),
	send_notifications boolean,
	moving_reason varchar(64),
	has_roommates boolean,
	has_security_deposit boolean,
	is_smoker boolean,
	has_prev_lawsuit boolean,
	has_prev_eviction boolean,
	can_credit_check boolean,
	has_pets boolean,
	additional_details_general varchar(64),
	move_in_date varchar(64),
	move_out_date varchar(64),
	additional_details_lease varchar(64)
);