create table users (
    id uuid primary key,
    full_name varchar(64),
    email varchar(64),
	user_status varchar(8),
	last_updated varchar(35),
	created_on varchar(35),
	phone_number varchar(16),
	nickname varchar(64),
	bio varchar(512),
	user_type varchar(64),
	send_notifications boolean,
	moving_reason varchar(512),
	has_roommates boolean,
	has_security_deposit boolean,
	is_smoker boolean,
	has_prev_lawsuit boolean,
	has_prev_eviction boolean,
	can_credit_check boolean,
	has_pets boolean,
	additional_details_general varchar(512),
	move_in_date varchar(10),
	move_out_date varchar(10),
	additional_details_lease varchar(512)
);