// Code generated by go-swagger; DO NOT EDIT.

package reference

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/turnkeyca/monolith/integration/models"
)

// CreateReferenceReader is a Reader for the CreateReference structure.
type CreateReferenceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateReferenceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewCreateReferenceNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateReferenceBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewCreateReferenceForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewCreateReferenceUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCreateReferenceInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateReferenceNoContent creates a CreateReferenceNoContent with default headers values
func NewCreateReferenceNoContent() *CreateReferenceNoContent {
	return &CreateReferenceNoContent{}
}

/* CreateReferenceNoContent describes a response with status code 204, with default header values.

No content is returned by this API endpoint
*/
type CreateReferenceNoContent struct {
}

func (o *CreateReferenceNoContent) Error() string {
	return fmt.Sprintf("[POST /v1/reference][%d] createReferenceNoContent ", 204)
}

func (o *CreateReferenceNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateReferenceBadRequest creates a CreateReferenceBadRequest with default headers values
func NewCreateReferenceBadRequest() *CreateReferenceBadRequest {
	return &CreateReferenceBadRequest{}
}

/* CreateReferenceBadRequest describes a response with status code 400, with default header values.

Generic error message returned as a string
*/
type CreateReferenceBadRequest struct {
	Payload models.GenericError
}

func (o *CreateReferenceBadRequest) Error() string {
	return fmt.Sprintf("[POST /v1/reference][%d] createReferenceBadRequest  %+v", 400, o.Payload)
}
func (o *CreateReferenceBadRequest) GetPayload() models.GenericError {
	return o.Payload
}

func (o *CreateReferenceBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateReferenceForbidden creates a CreateReferenceForbidden with default headers values
func NewCreateReferenceForbidden() *CreateReferenceForbidden {
	return &CreateReferenceForbidden{}
}

/* CreateReferenceForbidden describes a response with status code 403, with default header values.

Generic error message returned as a string
*/
type CreateReferenceForbidden struct {
	Payload models.GenericError
}

func (o *CreateReferenceForbidden) Error() string {
	return fmt.Sprintf("[POST /v1/reference][%d] createReferenceForbidden  %+v", 403, o.Payload)
}
func (o *CreateReferenceForbidden) GetPayload() models.GenericError {
	return o.Payload
}

func (o *CreateReferenceForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateReferenceUnprocessableEntity creates a CreateReferenceUnprocessableEntity with default headers values
func NewCreateReferenceUnprocessableEntity() *CreateReferenceUnprocessableEntity {
	return &CreateReferenceUnprocessableEntity{}
}

/* CreateReferenceUnprocessableEntity describes a response with status code 422, with default header values.

Generic error message returned as a string
*/
type CreateReferenceUnprocessableEntity struct {
	Payload models.GenericError
}

func (o *CreateReferenceUnprocessableEntity) Error() string {
	return fmt.Sprintf("[POST /v1/reference][%d] createReferenceUnprocessableEntity  %+v", 422, o.Payload)
}
func (o *CreateReferenceUnprocessableEntity) GetPayload() models.GenericError {
	return o.Payload
}

func (o *CreateReferenceUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateReferenceInternalServerError creates a CreateReferenceInternalServerError with default headers values
func NewCreateReferenceInternalServerError() *CreateReferenceInternalServerError {
	return &CreateReferenceInternalServerError{}
}

/* CreateReferenceInternalServerError describes a response with status code 500, with default header values.

Generic error message returned as a string
*/
type CreateReferenceInternalServerError struct {
	Payload models.GenericError
}

func (o *CreateReferenceInternalServerError) Error() string {
	return fmt.Sprintf("[POST /v1/reference][%d] createReferenceInternalServerError  %+v", 500, o.Payload)
}
func (o *CreateReferenceInternalServerError) GetPayload() models.GenericError {
	return o.Payload
}

func (o *CreateReferenceInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
