// Code generated by go-swagger; DO NOT EDIT.

package reference

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/turnkeyca/monolith/integration/models"
)

// DeleteReferenceReader is a Reader for the DeleteReference structure.
type DeleteReferenceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteReferenceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteReferenceNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewDeleteReferenceForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteReferenceInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteReferenceNoContent creates a DeleteReferenceNoContent with default headers values
func NewDeleteReferenceNoContent() *DeleteReferenceNoContent {
	return &DeleteReferenceNoContent{}
}

/* DeleteReferenceNoContent describes a response with status code 204, with default header values.

No content is returned by this API endpoint
*/
type DeleteReferenceNoContent struct {
}

func (o *DeleteReferenceNoContent) Error() string {
	return fmt.Sprintf("[DELETE /v1/reference/{id}][%d] deleteReferenceNoContent ", 204)
}

func (o *DeleteReferenceNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteReferenceForbidden creates a DeleteReferenceForbidden with default headers values
func NewDeleteReferenceForbidden() *DeleteReferenceForbidden {
	return &DeleteReferenceForbidden{}
}

/* DeleteReferenceForbidden describes a response with status code 403, with default header values.

Generic error message returned as a string
*/
type DeleteReferenceForbidden struct {
	Payload models.GenericError
}

func (o *DeleteReferenceForbidden) Error() string {
	return fmt.Sprintf("[DELETE /v1/reference/{id}][%d] deleteReferenceForbidden  %+v", 403, o.Payload)
}
func (o *DeleteReferenceForbidden) GetPayload() models.GenericError {
	return o.Payload
}

func (o *DeleteReferenceForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteReferenceInternalServerError creates a DeleteReferenceInternalServerError with default headers values
func NewDeleteReferenceInternalServerError() *DeleteReferenceInternalServerError {
	return &DeleteReferenceInternalServerError{}
}

/* DeleteReferenceInternalServerError describes a response with status code 500, with default header values.

Generic error message returned as a string
*/
type DeleteReferenceInternalServerError struct {
	Payload models.GenericError
}

func (o *DeleteReferenceInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /v1/reference/{id}][%d] deleteReferenceInternalServerError  %+v", 500, o.Payload)
}
func (o *DeleteReferenceInternalServerError) GetPayload() models.GenericError {
	return o.Payload
}

func (o *DeleteReferenceInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
