// Code generated by go-swagger; DO NOT EDIT.

package reference

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetReferencesByUserIDParams creates a new GetReferencesByUserIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetReferencesByUserIDParams() *GetReferencesByUserIDParams {
	return &GetReferencesByUserIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetReferencesByUserIDParamsWithTimeout creates a new GetReferencesByUserIDParams object
// with the ability to set a timeout on a request.
func NewGetReferencesByUserIDParamsWithTimeout(timeout time.Duration) *GetReferencesByUserIDParams {
	return &GetReferencesByUserIDParams{
		timeout: timeout,
	}
}

// NewGetReferencesByUserIDParamsWithContext creates a new GetReferencesByUserIDParams object
// with the ability to set a context for a request.
func NewGetReferencesByUserIDParamsWithContext(ctx context.Context) *GetReferencesByUserIDParams {
	return &GetReferencesByUserIDParams{
		Context: ctx,
	}
}

// NewGetReferencesByUserIDParamsWithHTTPClient creates a new GetReferencesByUserIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetReferencesByUserIDParamsWithHTTPClient(client *http.Client) *GetReferencesByUserIDParams {
	return &GetReferencesByUserIDParams{
		HTTPClient: client,
	}
}

/* GetReferencesByUserIDParams contains all the parameters to send to the API endpoint
   for the get references by user Id operation.

   Typically these are written to a http.Request.
*/
type GetReferencesByUserIDParams struct {

	// Token.
	Token string

	/* UserID.

	   The user id
	*/
	UserID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get references by user Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetReferencesByUserIDParams) WithDefaults() *GetReferencesByUserIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get references by user Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetReferencesByUserIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get references by user Id params
func (o *GetReferencesByUserIDParams) WithTimeout(timeout time.Duration) *GetReferencesByUserIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get references by user Id params
func (o *GetReferencesByUserIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get references by user Id params
func (o *GetReferencesByUserIDParams) WithContext(ctx context.Context) *GetReferencesByUserIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get references by user Id params
func (o *GetReferencesByUserIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get references by user Id params
func (o *GetReferencesByUserIDParams) WithHTTPClient(client *http.Client) *GetReferencesByUserIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get references by user Id params
func (o *GetReferencesByUserIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithToken adds the token to the get references by user Id params
func (o *GetReferencesByUserIDParams) WithToken(token string) *GetReferencesByUserIDParams {
	o.SetToken(token)
	return o
}

// SetToken adds the token to the get references by user Id params
func (o *GetReferencesByUserIDParams) SetToken(token string) {
	o.Token = token
}

// WithUserID adds the userID to the get references by user Id params
func (o *GetReferencesByUserIDParams) WithUserID(userID string) *GetReferencesByUserIDParams {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the get references by user Id params
func (o *GetReferencesByUserIDParams) SetUserID(userID string) {
	o.UserID = userID
}

// WriteToRequest writes these params to a swagger request
func (o *GetReferencesByUserIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Token
	if err := r.SetHeaderParam("Token", o.Token); err != nil {
		return err
	}

	// query param userId
	qrUserID := o.UserID
	qUserID := qrUserID
	if qUserID != "" {

		if err := r.SetQueryParam("userId", qUserID); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
