// Code generated by go-swagger; DO NOT EDIT.

package reference

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetReferenceParams creates a new GetReferenceParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetReferenceParams() *GetReferenceParams {
	return &GetReferenceParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetReferenceParamsWithTimeout creates a new GetReferenceParams object
// with the ability to set a timeout on a request.
func NewGetReferenceParamsWithTimeout(timeout time.Duration) *GetReferenceParams {
	return &GetReferenceParams{
		timeout: timeout,
	}
}

// NewGetReferenceParamsWithContext creates a new GetReferenceParams object
// with the ability to set a context for a request.
func NewGetReferenceParamsWithContext(ctx context.Context) *GetReferenceParams {
	return &GetReferenceParams{
		Context: ctx,
	}
}

// NewGetReferenceParamsWithHTTPClient creates a new GetReferenceParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetReferenceParamsWithHTTPClient(client *http.Client) *GetReferenceParams {
	return &GetReferenceParams{
		HTTPClient: client,
	}
}

/* GetReferenceParams contains all the parameters to send to the API endpoint
   for the get reference operation.

   Typically these are written to a http.Request.
*/
type GetReferenceParams struct {

	// Token.
	Token string

	/* ID.

	   The id of the reference for which the operation relates
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get reference params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetReferenceParams) WithDefaults() *GetReferenceParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get reference params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetReferenceParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get reference params
func (o *GetReferenceParams) WithTimeout(timeout time.Duration) *GetReferenceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get reference params
func (o *GetReferenceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get reference params
func (o *GetReferenceParams) WithContext(ctx context.Context) *GetReferenceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get reference params
func (o *GetReferenceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get reference params
func (o *GetReferenceParams) WithHTTPClient(client *http.Client) *GetReferenceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get reference params
func (o *GetReferenceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithToken adds the token to the get reference params
func (o *GetReferenceParams) WithToken(token string) *GetReferenceParams {
	o.SetToken(token)
	return o
}

// SetToken adds the token to the get reference params
func (o *GetReferenceParams) SetToken(token string) {
	o.Token = token
}

// WithID adds the id to the get reference params
func (o *GetReferenceParams) WithID(id string) *GetReferenceParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get reference params
func (o *GetReferenceParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetReferenceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Token
	if err := r.SetHeaderParam("Token", o.Token); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
