// Code generated by go-swagger; DO NOT EDIT.

package reference

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/turnkeyca/monolith/integration/models"
)

// GetReferencesByUserIDReader is a Reader for the GetReferencesByUserID structure.
type GetReferencesByUserIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetReferencesByUserIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetReferencesByUserIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewGetReferencesByUserIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetReferencesByUserIDOK creates a GetReferencesByUserIDOK with default headers values
func NewGetReferencesByUserIDOK() *GetReferencesByUserIDOK {
	return &GetReferencesByUserIDOK{}
}

/* GetReferencesByUserIDOK describes a response with status code 200, with default header values.

A list of references
*/
type GetReferencesByUserIDOK struct {
	Payload []*models.ReferenceDto
}

func (o *GetReferencesByUserIDOK) Error() string {
	return fmt.Sprintf("[GET /v1/reference][%d] getReferencesByUserIdOK  %+v", 200, o.Payload)
}
func (o *GetReferencesByUserIDOK) GetPayload() []*models.ReferenceDto {
	return o.Payload
}

func (o *GetReferencesByUserIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetReferencesByUserIDInternalServerError creates a GetReferencesByUserIDInternalServerError with default headers values
func NewGetReferencesByUserIDInternalServerError() *GetReferencesByUserIDInternalServerError {
	return &GetReferencesByUserIDInternalServerError{}
}

/* GetReferencesByUserIDInternalServerError describes a response with status code 500, with default header values.

Generic error message returned as a string
*/
type GetReferencesByUserIDInternalServerError struct {
	Payload models.GenericError
}

func (o *GetReferencesByUserIDInternalServerError) Error() string {
	return fmt.Sprintf("[GET /v1/reference][%d] getReferencesByUserIdInternalServerError  %+v", 500, o.Payload)
}
func (o *GetReferencesByUserIDInternalServerError) GetPayload() models.GenericError {
	return o.Payload
}

func (o *GetReferencesByUserIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
