// Code generated by go-swagger; DO NOT EDIT.

package reference

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/turnkeyca/monolith/integration/models"
)

// NewUpdateReferenceParams creates a new UpdateReferenceParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateReferenceParams() *UpdateReferenceParams {
	return &UpdateReferenceParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateReferenceParamsWithTimeout creates a new UpdateReferenceParams object
// with the ability to set a timeout on a request.
func NewUpdateReferenceParamsWithTimeout(timeout time.Duration) *UpdateReferenceParams {
	return &UpdateReferenceParams{
		timeout: timeout,
	}
}

// NewUpdateReferenceParamsWithContext creates a new UpdateReferenceParams object
// with the ability to set a context for a request.
func NewUpdateReferenceParamsWithContext(ctx context.Context) *UpdateReferenceParams {
	return &UpdateReferenceParams{
		Context: ctx,
	}
}

// NewUpdateReferenceParamsWithHTTPClient creates a new UpdateReferenceParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateReferenceParamsWithHTTPClient(client *http.Client) *UpdateReferenceParams {
	return &UpdateReferenceParams{
		HTTPClient: client,
	}
}

/* UpdateReferenceParams contains all the parameters to send to the API endpoint
   for the update reference operation.

   Typically these are written to a http.Request.
*/
type UpdateReferenceParams struct {

	// Body.
	Body *models.ReferenceDto

	// Token.
	Token string

	/* ID.

	   The id of the reference for which the operation relates
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update reference params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateReferenceParams) WithDefaults() *UpdateReferenceParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update reference params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateReferenceParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update reference params
func (o *UpdateReferenceParams) WithTimeout(timeout time.Duration) *UpdateReferenceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update reference params
func (o *UpdateReferenceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update reference params
func (o *UpdateReferenceParams) WithContext(ctx context.Context) *UpdateReferenceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update reference params
func (o *UpdateReferenceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update reference params
func (o *UpdateReferenceParams) WithHTTPClient(client *http.Client) *UpdateReferenceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update reference params
func (o *UpdateReferenceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update reference params
func (o *UpdateReferenceParams) WithBody(body *models.ReferenceDto) *UpdateReferenceParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update reference params
func (o *UpdateReferenceParams) SetBody(body *models.ReferenceDto) {
	o.Body = body
}

// WithToken adds the token to the update reference params
func (o *UpdateReferenceParams) WithToken(token string) *UpdateReferenceParams {
	o.SetToken(token)
	return o
}

// SetToken adds the token to the update reference params
func (o *UpdateReferenceParams) SetToken(token string) {
	o.Token = token
}

// WithID adds the id to the update reference params
func (o *UpdateReferenceParams) WithID(id string) *UpdateReferenceParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the update reference params
func (o *UpdateReferenceParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateReferenceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// header param Token
	if err := r.SetHeaderParam("Token", o.Token); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.Id); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
