// Code generated by go-swagger; DO NOT EDIT.

package roommate

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/turnkeyca/monolith/integration/models"
)

// NewCreateRoommateParams creates a new CreateRoommateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateRoommateParams() *CreateRoommateParams {
	return &CreateRoommateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateRoommateParamsWithTimeout creates a new CreateRoommateParams object
// with the ability to set a timeout on a request.
func NewCreateRoommateParamsWithTimeout(timeout time.Duration) *CreateRoommateParams {
	return &CreateRoommateParams{
		timeout: timeout,
	}
}

// NewCreateRoommateParamsWithContext creates a new CreateRoommateParams object
// with the ability to set a context for a request.
func NewCreateRoommateParamsWithContext(ctx context.Context) *CreateRoommateParams {
	return &CreateRoommateParams{
		Context: ctx,
	}
}

// NewCreateRoommateParamsWithHTTPClient creates a new CreateRoommateParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateRoommateParamsWithHTTPClient(client *http.Client) *CreateRoommateParams {
	return &CreateRoommateParams{
		HTTPClient: client,
	}
}

/* CreateRoommateParams contains all the parameters to send to the API endpoint
   for the create roommate operation.

   Typically these are written to a http.Request.
*/
type CreateRoommateParams struct {

	// Body.
	Body *models.RoommateDto

	// Token.
	Token string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create roommate params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateRoommateParams) WithDefaults() *CreateRoommateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create roommate params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateRoommateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create roommate params
func (o *CreateRoommateParams) WithTimeout(timeout time.Duration) *CreateRoommateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create roommate params
func (o *CreateRoommateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create roommate params
func (o *CreateRoommateParams) WithContext(ctx context.Context) *CreateRoommateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create roommate params
func (o *CreateRoommateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create roommate params
func (o *CreateRoommateParams) WithHTTPClient(client *http.Client) *CreateRoommateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create roommate params
func (o *CreateRoommateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create roommate params
func (o *CreateRoommateParams) WithBody(body *models.RoommateDto) *CreateRoommateParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create roommate params
func (o *CreateRoommateParams) SetBody(body *models.RoommateDto) {
	o.Body = body
}

// WithToken adds the token to the create roommate params
func (o *CreateRoommateParams) WithToken(token string) *CreateRoommateParams {
	o.SetToken(token)
	return o
}

// SetToken adds the token to the create roommate params
func (o *CreateRoommateParams) SetToken(token string) {
	o.Token = token
}

// WriteToRequest writes these params to a swagger request
func (o *CreateRoommateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// header param Token
	if err := r.SetHeaderParam("Token", o.Token); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
