// Code generated by go-swagger; DO NOT EDIT.

package roommate

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/turnkeyca/monolith/integration/models"
)

// CreateRoommateReader is a Reader for the CreateRoommate structure.
type CreateRoommateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateRoommateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewCreateRoommateNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateRoommateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewCreateRoommateUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCreateRoommateInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateRoommateNoContent creates a CreateRoommateNoContent with default headers values
func NewCreateRoommateNoContent() *CreateRoommateNoContent {
	return &CreateRoommateNoContent{}
}

/* CreateRoommateNoContent describes a response with status code 204, with default header values.

No content is returned by this API endpoint
*/
type CreateRoommateNoContent struct {
}

func (o *CreateRoommateNoContent) Error() string {
	return fmt.Sprintf("[POST /v1/roommate][%d] createRoommateNoContent ", 204)
}

func (o *CreateRoommateNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateRoommateBadRequest creates a CreateRoommateBadRequest with default headers values
func NewCreateRoommateBadRequest() *CreateRoommateBadRequest {
	return &CreateRoommateBadRequest{}
}

/* CreateRoommateBadRequest describes a response with status code 400, with default header values.

Generic error message returned as a string
*/
type CreateRoommateBadRequest struct {
	Payload models.GenericError
}

func (o *CreateRoommateBadRequest) Error() string {
	return fmt.Sprintf("[POST /v1/roommate][%d] createRoommateBadRequest  %+v", 400, o.Payload)
}
func (o *CreateRoommateBadRequest) GetPayload() models.GenericError {
	return o.Payload
}

func (o *CreateRoommateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateRoommateUnprocessableEntity creates a CreateRoommateUnprocessableEntity with default headers values
func NewCreateRoommateUnprocessableEntity() *CreateRoommateUnprocessableEntity {
	return &CreateRoommateUnprocessableEntity{}
}

/* CreateRoommateUnprocessableEntity describes a response with status code 422, with default header values.

Generic error message returned as a string
*/
type CreateRoommateUnprocessableEntity struct {
	Payload models.GenericError
}

func (o *CreateRoommateUnprocessableEntity) Error() string {
	return fmt.Sprintf("[POST /v1/roommate][%d] createRoommateUnprocessableEntity  %+v", 422, o.Payload)
}
func (o *CreateRoommateUnprocessableEntity) GetPayload() models.GenericError {
	return o.Payload
}

func (o *CreateRoommateUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateRoommateInternalServerError creates a CreateRoommateInternalServerError with default headers values
func NewCreateRoommateInternalServerError() *CreateRoommateInternalServerError {
	return &CreateRoommateInternalServerError{}
}

/* CreateRoommateInternalServerError describes a response with status code 500, with default header values.

Generic error message returned as a string
*/
type CreateRoommateInternalServerError struct {
	Payload models.GenericError
}

func (o *CreateRoommateInternalServerError) Error() string {
	return fmt.Sprintf("[POST /v1/roommate][%d] createRoommateInternalServerError  %+v", 500, o.Payload)
}
func (o *CreateRoommateInternalServerError) GetPayload() models.GenericError {
	return o.Payload
}

func (o *CreateRoommateInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
