// Code generated by go-swagger; DO NOT EDIT.

package roommate

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/turnkeyca/monolith/integration/models"
)

// DeleteRoommateReader is a Reader for the DeleteRoommate structure.
type DeleteRoommateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteRoommateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteRoommateNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewDeleteRoommateForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteRoommateInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteRoommateNoContent creates a DeleteRoommateNoContent with default headers values
func NewDeleteRoommateNoContent() *DeleteRoommateNoContent {
	return &DeleteRoommateNoContent{}
}

/* DeleteRoommateNoContent describes a response with status code 204, with default header values.

No content is returned by this API endpoint
*/
type DeleteRoommateNoContent struct {
}

func (o *DeleteRoommateNoContent) Error() string {
	return fmt.Sprintf("[DELETE /v1/roommate/{id}][%d] deleteRoommateNoContent ", 204)
}

func (o *DeleteRoommateNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteRoommateForbidden creates a DeleteRoommateForbidden with default headers values
func NewDeleteRoommateForbidden() *DeleteRoommateForbidden {
	return &DeleteRoommateForbidden{}
}

/* DeleteRoommateForbidden describes a response with status code 403, with default header values.

Generic error message returned as a string
*/
type DeleteRoommateForbidden struct {
	Payload models.GenericError
}

func (o *DeleteRoommateForbidden) Error() string {
	return fmt.Sprintf("[DELETE /v1/roommate/{id}][%d] deleteRoommateForbidden  %+v", 403, o.Payload)
}
func (o *DeleteRoommateForbidden) GetPayload() models.GenericError {
	return o.Payload
}

func (o *DeleteRoommateForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteRoommateInternalServerError creates a DeleteRoommateInternalServerError with default headers values
func NewDeleteRoommateInternalServerError() *DeleteRoommateInternalServerError {
	return &DeleteRoommateInternalServerError{}
}

/* DeleteRoommateInternalServerError describes a response with status code 500, with default header values.

Generic error message returned as a string
*/
type DeleteRoommateInternalServerError struct {
	Payload models.GenericError
}

func (o *DeleteRoommateInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /v1/roommate/{id}][%d] deleteRoommateInternalServerError  %+v", 500, o.Payload)
}
func (o *DeleteRoommateInternalServerError) GetPayload() models.GenericError {
	return o.Payload
}

func (o *DeleteRoommateInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
