// Code generated by go-swagger; DO NOT EDIT.

package roommate

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/turnkeyca/monolith/integration/models"
)

// GetRoommateReader is a Reader for the GetRoommate structure.
type GetRoommateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetRoommateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetRoommateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewGetRoommateForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetRoommateNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetRoommateInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetRoommateOK creates a GetRoommateOK with default headers values
func NewGetRoommateOK() *GetRoommateOK {
	return &GetRoommateOK{}
}

/* GetRoommateOK describes a response with status code 200, with default header values.

A roommate
*/
type GetRoommateOK struct {
	Payload *models.RoommateDto
}

func (o *GetRoommateOK) Error() string {
	return fmt.Sprintf("[GET /v1/roommate/{id}][%d] getRoommateOK  %+v", 200, o.Payload)
}
func (o *GetRoommateOK) GetPayload() *models.RoommateDto {
	return o.Payload
}

func (o *GetRoommateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RoommateDto)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetRoommateForbidden creates a GetRoommateForbidden with default headers values
func NewGetRoommateForbidden() *GetRoommateForbidden {
	return &GetRoommateForbidden{}
}

/* GetRoommateForbidden describes a response with status code 403, with default header values.

Generic error message returned as a string
*/
type GetRoommateForbidden struct {
	Payload models.GenericError
}

func (o *GetRoommateForbidden) Error() string {
	return fmt.Sprintf("[GET /v1/roommate/{id}][%d] getRoommateForbidden  %+v", 403, o.Payload)
}
func (o *GetRoommateForbidden) GetPayload() models.GenericError {
	return o.Payload
}

func (o *GetRoommateForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetRoommateNotFound creates a GetRoommateNotFound with default headers values
func NewGetRoommateNotFound() *GetRoommateNotFound {
	return &GetRoommateNotFound{}
}

/* GetRoommateNotFound describes a response with status code 404, with default header values.

Generic error message returned as a string
*/
type GetRoommateNotFound struct {
	Payload models.GenericError
}

func (o *GetRoommateNotFound) Error() string {
	return fmt.Sprintf("[GET /v1/roommate/{id}][%d] getRoommateNotFound  %+v", 404, o.Payload)
}
func (o *GetRoommateNotFound) GetPayload() models.GenericError {
	return o.Payload
}

func (o *GetRoommateNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetRoommateInternalServerError creates a GetRoommateInternalServerError with default headers values
func NewGetRoommateInternalServerError() *GetRoommateInternalServerError {
	return &GetRoommateInternalServerError{}
}

/* GetRoommateInternalServerError describes a response with status code 500, with default header values.

Generic error message returned as a string
*/
type GetRoommateInternalServerError struct {
	Payload models.GenericError
}

func (o *GetRoommateInternalServerError) Error() string {
	return fmt.Sprintf("[GET /v1/roommate/{id}][%d] getRoommateInternalServerError  %+v", 500, o.Payload)
}
func (o *GetRoommateInternalServerError) GetPayload() models.GenericError {
	return o.Payload
}

func (o *GetRoommateInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
