// Code generated by go-swagger; DO NOT EDIT.

package roommate

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetRoommatesByUserIDParams creates a new GetRoommatesByUserIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetRoommatesByUserIDParams() *GetRoommatesByUserIDParams {
	return &GetRoommatesByUserIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetRoommatesByUserIDParamsWithTimeout creates a new GetRoommatesByUserIDParams object
// with the ability to set a timeout on a request.
func NewGetRoommatesByUserIDParamsWithTimeout(timeout time.Duration) *GetRoommatesByUserIDParams {
	return &GetRoommatesByUserIDParams{
		timeout: timeout,
	}
}

// NewGetRoommatesByUserIDParamsWithContext creates a new GetRoommatesByUserIDParams object
// with the ability to set a context for a request.
func NewGetRoommatesByUserIDParamsWithContext(ctx context.Context) *GetRoommatesByUserIDParams {
	return &GetRoommatesByUserIDParams{
		Context: ctx,
	}
}

// NewGetRoommatesByUserIDParamsWithHTTPClient creates a new GetRoommatesByUserIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetRoommatesByUserIDParamsWithHTTPClient(client *http.Client) *GetRoommatesByUserIDParams {
	return &GetRoommatesByUserIDParams{
		HTTPClient: client,
	}
}

/* GetRoommatesByUserIDParams contains all the parameters to send to the API endpoint
   for the get roommates by user Id operation.

   Typically these are written to a http.Request.
*/
type GetRoommatesByUserIDParams struct {

	// Token.
	Token string

	/* UserID.

	   The user id
	*/
	UserID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get roommates by user Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetRoommatesByUserIDParams) WithDefaults() *GetRoommatesByUserIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get roommates by user Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetRoommatesByUserIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get roommates by user Id params
func (o *GetRoommatesByUserIDParams) WithTimeout(timeout time.Duration) *GetRoommatesByUserIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get roommates by user Id params
func (o *GetRoommatesByUserIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get roommates by user Id params
func (o *GetRoommatesByUserIDParams) WithContext(ctx context.Context) *GetRoommatesByUserIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get roommates by user Id params
func (o *GetRoommatesByUserIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get roommates by user Id params
func (o *GetRoommatesByUserIDParams) WithHTTPClient(client *http.Client) *GetRoommatesByUserIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get roommates by user Id params
func (o *GetRoommatesByUserIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithToken adds the token to the get roommates by user Id params
func (o *GetRoommatesByUserIDParams) WithToken(token string) *GetRoommatesByUserIDParams {
	o.SetToken(token)
	return o
}

// SetToken adds the token to the get roommates by user Id params
func (o *GetRoommatesByUserIDParams) SetToken(token string) {
	o.Token = token
}

// WithUserID adds the userID to the get roommates by user Id params
func (o *GetRoommatesByUserIDParams) WithUserID(userID string) *GetRoommatesByUserIDParams {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the get roommates by user Id params
func (o *GetRoommatesByUserIDParams) SetUserID(userID string) {
	o.UserID = userID
}

// WriteToRequest writes these params to a swagger request
func (o *GetRoommatesByUserIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Token
	if err := r.SetHeaderParam("Token", o.Token); err != nil {
		return err
	}

	// query param userId
	qrUserID := o.UserId
	qUserID := qrUserID
	if qUserID != "" {

		if err := r.SetQueryParam("userId", qUserID); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
