// Code generated by go-swagger; DO NOT EDIT.

package roommate

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetRoommateParams creates a new GetRoommateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetRoommateParams() *GetRoommateParams {
	return &GetRoommateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetRoommateParamsWithTimeout creates a new GetRoommateParams object
// with the ability to set a timeout on a request.
func NewGetRoommateParamsWithTimeout(timeout time.Duration) *GetRoommateParams {
	return &GetRoommateParams{
		timeout: timeout,
	}
}

// NewGetRoommateParamsWithContext creates a new GetRoommateParams object
// with the ability to set a context for a request.
func NewGetRoommateParamsWithContext(ctx context.Context) *GetRoommateParams {
	return &GetRoommateParams{
		Context: ctx,
	}
}

// NewGetRoommateParamsWithHTTPClient creates a new GetRoommateParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetRoommateParamsWithHTTPClient(client *http.Client) *GetRoommateParams {
	return &GetRoommateParams{
		HTTPClient: client,
	}
}

/* GetRoommateParams contains all the parameters to send to the API endpoint
   for the get roommate operation.

   Typically these are written to a http.Request.
*/
type GetRoommateParams struct {

	// Token.
	Token string

	/* ID.

	   The id of the roommate for which the operation relates
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get roommate params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetRoommateParams) WithDefaults() *GetRoommateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get roommate params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetRoommateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get roommate params
func (o *GetRoommateParams) WithTimeout(timeout time.Duration) *GetRoommateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get roommate params
func (o *GetRoommateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get roommate params
func (o *GetRoommateParams) WithContext(ctx context.Context) *GetRoommateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get roommate params
func (o *GetRoommateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get roommate params
func (o *GetRoommateParams) WithHTTPClient(client *http.Client) *GetRoommateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get roommate params
func (o *GetRoommateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithToken adds the token to the get roommate params
func (o *GetRoommateParams) WithToken(token string) *GetRoommateParams {
	o.SetToken(token)
	return o
}

// SetToken adds the token to the get roommate params
func (o *GetRoommateParams) SetToken(token string) {
	o.Token = token
}

// WithID adds the id to the get roommate params
func (o *GetRoommateParams) WithID(id string) *GetRoommateParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get roommate params
func (o *GetRoommateParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetRoommateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Token
	if err := r.SetHeaderParam("Token", o.Token); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.Id); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
