// Code generated by go-swagger; DO NOT EDIT.

package roommate

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/turnkeyca/monolith/integration/models"
)

// GetRoommatesByUserIDReader is a Reader for the GetRoommatesByUserID structure.
type GetRoommatesByUserIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetRoommatesByUserIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetRoommatesByUserIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewGetRoommatesByUserIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetRoommatesByUserIDOK creates a GetRoommatesByUserIDOK with default headers values
func NewGetRoommatesByUserIDOK() *GetRoommatesByUserIDOK {
	return &GetRoommatesByUserIDOK{}
}

/* GetRoommatesByUserIDOK describes a response with status code 200, with default header values.

A list of roommates
*/
type GetRoommatesByUserIDOK struct {
	Payload []*models.RoommateDto
}

func (o *GetRoommatesByUserIDOK) Error() string {
	return fmt.Sprintf("[GET /v1/roommate][%d] getRoommatesByUserIdOK  %+v", 200, o.Payload)
}
func (o *GetRoommatesByUserIDOK) GetPayload() []*models.RoommateDto {
	return o.Payload
}

func (o *GetRoommatesByUserIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetRoommatesByUserIDInternalServerError creates a GetRoommatesByUserIDInternalServerError with default headers values
func NewGetRoommatesByUserIDInternalServerError() *GetRoommatesByUserIDInternalServerError {
	return &GetRoommatesByUserIDInternalServerError{}
}

/* GetRoommatesByUserIDInternalServerError describes a response with status code 500, with default header values.

Generic error message returned as a string
*/
type GetRoommatesByUserIDInternalServerError struct {
	Payload models.GenericError
}

func (o *GetRoommatesByUserIDInternalServerError) Error() string {
	return fmt.Sprintf("[GET /v1/roommate][%d] getRoommatesByUserIdInternalServerError  %+v", 500, o.Payload)
}
func (o *GetRoommatesByUserIDInternalServerError) GetPayload() models.GenericError {
	return o.Payload
}

func (o *GetRoommatesByUserIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
