// Code generated by go-swagger; DO NOT EDIT.

package roommate

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/turnkeyca/monolith/integration/models"
)

// UpdateRoommateReader is a Reader for the UpdateRoommate structure.
type UpdateRoommateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateRoommateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewUpdateRoommateNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewUpdateRoommateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewUpdateRoommateForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewUpdateRoommateNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewUpdateRoommateUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewUpdateRoommateInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewUpdateRoommateNoContent creates a UpdateRoommateNoContent with default headers values
func NewUpdateRoommateNoContent() *UpdateRoommateNoContent {
	return &UpdateRoommateNoContent{}
}

/* UpdateRoommateNoContent describes a response with status code 204, with default header values.

No content is returned by this API endpoint
*/
type UpdateRoommateNoContent struct {
}

func (o *UpdateRoommateNoContent) Error() string {
	return fmt.Sprintf("[PUT /v1/roommate/{id}][%d] updateRoommateNoContent ", 204)
}

func (o *UpdateRoommateNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateRoommateBadRequest creates a UpdateRoommateBadRequest with default headers values
func NewUpdateRoommateBadRequest() *UpdateRoommateBadRequest {
	return &UpdateRoommateBadRequest{}
}

/* UpdateRoommateBadRequest describes a response with status code 400, with default header values.

Generic error message returned as a string
*/
type UpdateRoommateBadRequest struct {
	Payload models.GenericError
}

func (o *UpdateRoommateBadRequest) Error() string {
	return fmt.Sprintf("[PUT /v1/roommate/{id}][%d] updateRoommateBadRequest  %+v", 400, o.Payload)
}
func (o *UpdateRoommateBadRequest) GetPayload() models.GenericError {
	return o.Payload
}

func (o *UpdateRoommateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateRoommateForbidden creates a UpdateRoommateForbidden with default headers values
func NewUpdateRoommateForbidden() *UpdateRoommateForbidden {
	return &UpdateRoommateForbidden{}
}

/* UpdateRoommateForbidden describes a response with status code 403, with default header values.

Generic error message returned as a string
*/
type UpdateRoommateForbidden struct {
	Payload models.GenericError
}

func (o *UpdateRoommateForbidden) Error() string {
	return fmt.Sprintf("[PUT /v1/roommate/{id}][%d] updateRoommateForbidden  %+v", 403, o.Payload)
}
func (o *UpdateRoommateForbidden) GetPayload() models.GenericError {
	return o.Payload
}

func (o *UpdateRoommateForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateRoommateNotFound creates a UpdateRoommateNotFound with default headers values
func NewUpdateRoommateNotFound() *UpdateRoommateNotFound {
	return &UpdateRoommateNotFound{}
}

/* UpdateRoommateNotFound describes a response with status code 404, with default header values.

Generic error message returned as a string
*/
type UpdateRoommateNotFound struct {
	Payload models.GenericError
}

func (o *UpdateRoommateNotFound) Error() string {
	return fmt.Sprintf("[PUT /v1/roommate/{id}][%d] updateRoommateNotFound  %+v", 404, o.Payload)
}
func (o *UpdateRoommateNotFound) GetPayload() models.GenericError {
	return o.Payload
}

func (o *UpdateRoommateNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateRoommateUnprocessableEntity creates a UpdateRoommateUnprocessableEntity with default headers values
func NewUpdateRoommateUnprocessableEntity() *UpdateRoommateUnprocessableEntity {
	return &UpdateRoommateUnprocessableEntity{}
}

/* UpdateRoommateUnprocessableEntity describes a response with status code 422, with default header values.

Generic error message returned as a string
*/
type UpdateRoommateUnprocessableEntity struct {
	Payload models.GenericError
}

func (o *UpdateRoommateUnprocessableEntity) Error() string {
	return fmt.Sprintf("[PUT /v1/roommate/{id}][%d] updateRoommateUnprocessableEntity  %+v", 422, o.Payload)
}
func (o *UpdateRoommateUnprocessableEntity) GetPayload() models.GenericError {
	return o.Payload
}

func (o *UpdateRoommateUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateRoommateInternalServerError creates a UpdateRoommateInternalServerError with default headers values
func NewUpdateRoommateInternalServerError() *UpdateRoommateInternalServerError {
	return &UpdateRoommateInternalServerError{}
}

/* UpdateRoommateInternalServerError describes a response with status code 500, with default header values.

Generic error message returned as a string
*/
type UpdateRoommateInternalServerError struct {
	Payload models.GenericError
}

func (o *UpdateRoommateInternalServerError) Error() string {
	return fmt.Sprintf("[PUT /v1/roommate/{id}][%d] updateRoommateInternalServerError  %+v", 500, o.Payload)
}
func (o *UpdateRoommateInternalServerError) GetPayload() models.GenericError {
	return o.Payload
}

func (o *UpdateRoommateInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
