// Code generated by go-swagger; DO NOT EDIT.

package roommate

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/turnkeyca/monolith/integration/models"
)

// NewUpdateRoommateParams creates a new UpdateRoommateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateRoommateParams() *UpdateRoommateParams {
	return &UpdateRoommateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateRoommateParamsWithTimeout creates a new UpdateRoommateParams object
// with the ability to set a timeout on a request.
func NewUpdateRoommateParamsWithTimeout(timeout time.Duration) *UpdateRoommateParams {
	return &UpdateRoommateParams{
		timeout: timeout,
	}
}

// NewUpdateRoommateParamsWithContext creates a new UpdateRoommateParams object
// with the ability to set a context for a request.
func NewUpdateRoommateParamsWithContext(ctx context.Context) *UpdateRoommateParams {
	return &UpdateRoommateParams{
		Context: ctx,
	}
}

// NewUpdateRoommateParamsWithHTTPClient creates a new UpdateRoommateParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateRoommateParamsWithHTTPClient(client *http.Client) *UpdateRoommateParams {
	return &UpdateRoommateParams{
		HTTPClient: client,
	}
}

/* UpdateRoommateParams contains all the parameters to send to the API endpoint
   for the update roommate operation.

   Typically these are written to a http.Request.
*/
type UpdateRoommateParams struct {

	// Body.
	Body *models.RoommateDto

	// Token.
	Token string

	/* ID.

	   The id of the roommate for which the operation relates
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update roommate params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateRoommateParams) WithDefaults() *UpdateRoommateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update roommate params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateRoommateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update roommate params
func (o *UpdateRoommateParams) WithTimeout(timeout time.Duration) *UpdateRoommateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update roommate params
func (o *UpdateRoommateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update roommate params
func (o *UpdateRoommateParams) WithContext(ctx context.Context) *UpdateRoommateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update roommate params
func (o *UpdateRoommateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update roommate params
func (o *UpdateRoommateParams) WithHTTPClient(client *http.Client) *UpdateRoommateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update roommate params
func (o *UpdateRoommateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update roommate params
func (o *UpdateRoommateParams) WithBody(body *models.RoommateDto) *UpdateRoommateParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update roommate params
func (o *UpdateRoommateParams) SetBody(body *models.RoommateDto) {
	o.Body = body
}

// WithToken adds the token to the update roommate params
func (o *UpdateRoommateParams) WithToken(token string) *UpdateRoommateParams {
	o.SetToken(token)
	return o
}

// SetToken adds the token to the update roommate params
func (o *UpdateRoommateParams) SetToken(token string) {
	o.Token = token
}

// WithID adds the id to the update roommate params
func (o *UpdateRoommateParams) WithID(id string) *UpdateRoommateParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the update roommate params
func (o *UpdateRoommateParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateRoommateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// header param Token
	if err := r.SetHeaderParam("Token", o.Token); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.Id); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
