// Code generated by go-swagger; DO NOT EDIT.

package employment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/turnkeyca/monolith/integration/models"
)

// NewCreateEmploymentParams creates a new CreateEmploymentParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateEmploymentParams() *CreateEmploymentParams {
	return &CreateEmploymentParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateEmploymentParamsWithTimeout creates a new CreateEmploymentParams object
// with the ability to set a timeout on a request.
func NewCreateEmploymentParamsWithTimeout(timeout time.Duration) *CreateEmploymentParams {
	return &CreateEmploymentParams{
		timeout: timeout,
	}
}

// NewCreateEmploymentParamsWithContext creates a new CreateEmploymentParams object
// with the ability to set a context for a request.
func NewCreateEmploymentParamsWithContext(ctx context.Context) *CreateEmploymentParams {
	return &CreateEmploymentParams{
		Context: ctx,
	}
}

// NewCreateEmploymentParamsWithHTTPClient creates a new CreateEmploymentParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateEmploymentParamsWithHTTPClient(client *http.Client) *CreateEmploymentParams {
	return &CreateEmploymentParams{
		HTTPClient: client,
	}
}

/* CreateEmploymentParams contains all the parameters to send to the API endpoint
   for the create employment operation.

   Typically these are written to a http.Request.
*/
type CreateEmploymentParams struct {

	// Body.
	Body *models.EmploymentDto

	// Token.
	Token string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create employment params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateEmploymentParams) WithDefaults() *CreateEmploymentParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create employment params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateEmploymentParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create employment params
func (o *CreateEmploymentParams) WithTimeout(timeout time.Duration) *CreateEmploymentParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create employment params
func (o *CreateEmploymentParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create employment params
func (o *CreateEmploymentParams) WithContext(ctx context.Context) *CreateEmploymentParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create employment params
func (o *CreateEmploymentParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create employment params
func (o *CreateEmploymentParams) WithHTTPClient(client *http.Client) *CreateEmploymentParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create employment params
func (o *CreateEmploymentParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create employment params
func (o *CreateEmploymentParams) WithBody(body *models.EmploymentDto) *CreateEmploymentParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create employment params
func (o *CreateEmploymentParams) SetBody(body *models.EmploymentDto) {
	o.Body = body
}

// WithToken adds the token to the create employment params
func (o *CreateEmploymentParams) WithToken(token string) *CreateEmploymentParams {
	o.SetToken(token)
	return o
}

// SetToken adds the token to the create employment params
func (o *CreateEmploymentParams) SetToken(token string) {
	o.Token = token
}

// WriteToRequest writes these params to a swagger request
func (o *CreateEmploymentParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// header param Token
	if err := r.SetHeaderParam("Token", o.Token); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
