// Code generated by go-swagger; DO NOT EDIT.

package employment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/turnkeyca/monolith/integration/models"
)

// CreateEmploymentReader is a Reader for the CreateEmployment structure.
type CreateEmploymentReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateEmploymentReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewCreateEmploymentNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateEmploymentBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewCreateEmploymentUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCreateEmploymentInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateEmploymentNoContent creates a CreateEmploymentNoContent with default headers values
func NewCreateEmploymentNoContent() *CreateEmploymentNoContent {
	return &CreateEmploymentNoContent{}
}

/* CreateEmploymentNoContent describes a response with status code 204, with default header values.

No content is returned by this API endpoint
*/
type CreateEmploymentNoContent struct {
}

func (o *CreateEmploymentNoContent) Error() string {
	return fmt.Sprintf("[POST /v1/employment][%d] createEmploymentNoContent ", 204)
}

func (o *CreateEmploymentNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateEmploymentBadRequest creates a CreateEmploymentBadRequest with default headers values
func NewCreateEmploymentBadRequest() *CreateEmploymentBadRequest {
	return &CreateEmploymentBadRequest{}
}

/* CreateEmploymentBadRequest describes a response with status code 400, with default header values.

Generic error message returned as a string
*/
type CreateEmploymentBadRequest struct {
	Payload models.GenericError
}

func (o *CreateEmploymentBadRequest) Error() string {
	return fmt.Sprintf("[POST /v1/employment][%d] createEmploymentBadRequest  %+v", 400, o.Payload)
}
func (o *CreateEmploymentBadRequest) GetPayload() models.GenericError {
	return o.Payload
}

func (o *CreateEmploymentBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateEmploymentUnprocessableEntity creates a CreateEmploymentUnprocessableEntity with default headers values
func NewCreateEmploymentUnprocessableEntity() *CreateEmploymentUnprocessableEntity {
	return &CreateEmploymentUnprocessableEntity{}
}

/* CreateEmploymentUnprocessableEntity describes a response with status code 422, with default header values.

Generic error message returned as a string
*/
type CreateEmploymentUnprocessableEntity struct {
	Payload models.GenericError
}

func (o *CreateEmploymentUnprocessableEntity) Error() string {
	return fmt.Sprintf("[POST /v1/employment][%d] createEmploymentUnprocessableEntity  %+v", 422, o.Payload)
}
func (o *CreateEmploymentUnprocessableEntity) GetPayload() models.GenericError {
	return o.Payload
}

func (o *CreateEmploymentUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateEmploymentInternalServerError creates a CreateEmploymentInternalServerError with default headers values
func NewCreateEmploymentInternalServerError() *CreateEmploymentInternalServerError {
	return &CreateEmploymentInternalServerError{}
}

/* CreateEmploymentInternalServerError describes a response with status code 500, with default header values.

Generic error message returned as a string
*/
type CreateEmploymentInternalServerError struct {
	Payload models.GenericError
}

func (o *CreateEmploymentInternalServerError) Error() string {
	return fmt.Sprintf("[POST /v1/employment][%d] createEmploymentInternalServerError  %+v", 500, o.Payload)
}
func (o *CreateEmploymentInternalServerError) GetPayload() models.GenericError {
	return o.Payload
}

func (o *CreateEmploymentInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
