// Code generated by go-swagger; DO NOT EDIT.

package employment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetEmploymentParams creates a new GetEmploymentParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetEmploymentParams() *GetEmploymentParams {
	return &GetEmploymentParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetEmploymentParamsWithTimeout creates a new GetEmploymentParams object
// with the ability to set a timeout on a request.
func NewGetEmploymentParamsWithTimeout(timeout time.Duration) *GetEmploymentParams {
	return &GetEmploymentParams{
		timeout: timeout,
	}
}

// NewGetEmploymentParamsWithContext creates a new GetEmploymentParams object
// with the ability to set a context for a request.
func NewGetEmploymentParamsWithContext(ctx context.Context) *GetEmploymentParams {
	return &GetEmploymentParams{
		Context: ctx,
	}
}

// NewGetEmploymentParamsWithHTTPClient creates a new GetEmploymentParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetEmploymentParamsWithHTTPClient(client *http.Client) *GetEmploymentParams {
	return &GetEmploymentParams{
		HTTPClient: client,
	}
}

/* GetEmploymentParams contains all the parameters to send to the API endpoint
   for the get employment operation.

   Typically these are written to a http.Request.
*/
type GetEmploymentParams struct {

	// Token.
	Token string

	/* ID.

	   The id of the employment for which the operation relates
	*/
	Id string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get employment params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetEmploymentParams) WithDefaults() *GetEmploymentParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get employment params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetEmploymentParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get employment params
func (o *GetEmploymentParams) WithTimeout(timeout time.Duration) *GetEmploymentParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get employment params
func (o *GetEmploymentParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get employment params
func (o *GetEmploymentParams) WithContext(ctx context.Context) *GetEmploymentParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get employment params
func (o *GetEmploymentParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get employment params
func (o *GetEmploymentParams) WithHTTPClient(client *http.Client) *GetEmploymentParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get employment params
func (o *GetEmploymentParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithToken adds the token to the get employment params
func (o *GetEmploymentParams) WithToken(token string) *GetEmploymentParams {
	o.SetToken(token)
	return o
}

// SetToken adds the token to the get employment params
func (o *GetEmploymentParams) SetToken(token string) {
	o.Token = token
}

// WithID adds the id to the get employment params
func (o *GetEmploymentParams) WithID(id string) *GetEmploymentParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get employment params
func (o *GetEmploymentParams) SetID(id string) {
	o.Id = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetEmploymentParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Token
	if err := r.SetHeaderParam("Token", o.Token); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.Id); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
