// Code generated by go-swagger; DO NOT EDIT.

package employment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/turnkeyca/monolith/integration/models"
)

// NewUpdateEmploymentParams creates a new UpdateEmploymentParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateEmploymentParams() *UpdateEmploymentParams {
	return &UpdateEmploymentParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateEmploymentParamsWithTimeout creates a new UpdateEmploymentParams object
// with the ability to set a timeout on a request.
func NewUpdateEmploymentParamsWithTimeout(timeout time.Duration) *UpdateEmploymentParams {
	return &UpdateEmploymentParams{
		timeout: timeout,
	}
}

// NewUpdateEmploymentParamsWithContext creates a new UpdateEmploymentParams object
// with the ability to set a context for a request.
func NewUpdateEmploymentParamsWithContext(ctx context.Context) *UpdateEmploymentParams {
	return &UpdateEmploymentParams{
		Context: ctx,
	}
}

// NewUpdateEmploymentParamsWithHTTPClient creates a new UpdateEmploymentParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateEmploymentParamsWithHTTPClient(client *http.Client) *UpdateEmploymentParams {
	return &UpdateEmploymentParams{
		HTTPClient: client,
	}
}

/* UpdateEmploymentParams contains all the parameters to send to the API endpoint
   for the update employment operation.

   Typically these are written to a http.Request.
*/
type UpdateEmploymentParams struct {

	// Body.
	Body *models.EmploymentDto

	// Token.
	Token string

	/* ID.

	   The id of the employment for which the operation relates
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update employment params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateEmploymentParams) WithDefaults() *UpdateEmploymentParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update employment params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateEmploymentParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update employment params
func (o *UpdateEmploymentParams) WithTimeout(timeout time.Duration) *UpdateEmploymentParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update employment params
func (o *UpdateEmploymentParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update employment params
func (o *UpdateEmploymentParams) WithContext(ctx context.Context) *UpdateEmploymentParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update employment params
func (o *UpdateEmploymentParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update employment params
func (o *UpdateEmploymentParams) WithHTTPClient(client *http.Client) *UpdateEmploymentParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update employment params
func (o *UpdateEmploymentParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update employment params
func (o *UpdateEmploymentParams) WithBody(body *models.EmploymentDto) *UpdateEmploymentParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update employment params
func (o *UpdateEmploymentParams) SetBody(body *models.EmploymentDto) {
	o.Body = body
}

// WithToken adds the token to the update employment params
func (o *UpdateEmploymentParams) WithToken(token string) *UpdateEmploymentParams {
	o.SetToken(token)
	return o
}

// SetToken adds the token to the update employment params
func (o *UpdateEmploymentParams) SetToken(token string) {
	o.Token = token
}

// WithID adds the id to the update employment params
func (o *UpdateEmploymentParams) WithID(id string) *UpdateEmploymentParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the update employment params
func (o *UpdateEmploymentParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateEmploymentParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// header param Token
	if err := r.SetHeaderParam("Token", o.Token); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.Id); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
