// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/turnkeyca/monolith/integration/models"
)

// NewRegisterNewTokenParams creates a new RegisterNewTokenParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewRegisterNewTokenParams() *RegisterNewTokenParams {
	return &RegisterNewTokenParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewRegisterNewTokenParamsWithTimeout creates a new RegisterNewTokenParams object
// with the ability to set a timeout on a request.
func NewRegisterNewTokenParamsWithTimeout(timeout time.Duration) *RegisterNewTokenParams {
	return &RegisterNewTokenParams{
		timeout: timeout,
	}
}

// NewRegisterNewTokenParamsWithContext creates a new RegisterNewTokenParams object
// with the ability to set a context for a request.
func NewRegisterNewTokenParamsWithContext(ctx context.Context) *RegisterNewTokenParams {
	return &RegisterNewTokenParams{
		Context: ctx,
	}
}

// NewRegisterNewTokenParamsWithHTTPClient creates a new RegisterNewTokenParams object
// with the ability to set a custom HTTPClient for a request.
func NewRegisterNewTokenParamsWithHTTPClient(client *http.Client) *RegisterNewTokenParams {
	return &RegisterNewTokenParams{
		HTTPClient: client,
	}
}

/* RegisterNewTokenParams contains all the parameters to send to the API endpoint
   for the register new token operation.

   Typically these are written to a http.Request.
*/
type RegisterNewTokenParams struct {

	// Body.
	Body *models.RegisterTokenDto

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the register new token params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RegisterNewTokenParams) WithDefaults() *RegisterNewTokenParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the register new token params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RegisterNewTokenParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the register new token params
func (o *RegisterNewTokenParams) WithTimeout(timeout time.Duration) *RegisterNewTokenParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the register new token params
func (o *RegisterNewTokenParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the register new token params
func (o *RegisterNewTokenParams) WithContext(ctx context.Context) *RegisterNewTokenParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the register new token params
func (o *RegisterNewTokenParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the register new token params
func (o *RegisterNewTokenParams) WithHTTPClient(client *http.Client) *RegisterNewTokenParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the register new token params
func (o *RegisterNewTokenParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the register new token params
func (o *RegisterNewTokenParams) WithBody(body *models.RegisterTokenDto) *RegisterNewTokenParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the register new token params
func (o *RegisterNewTokenParams) SetBody(body *models.RegisterTokenDto) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *RegisterNewTokenParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
