// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/turnkeyca/monolith/integration/models"
)

// ActivateUserReader is a Reader for the ActivateUser structure.
type ActivateUserReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ActivateUserReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewActivateUserNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewActivateUserForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewActivateUserInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewActivateUserNoContent creates a ActivateUserNoContent with default headers values
func NewActivateUserNoContent() *ActivateUserNoContent {
	return &ActivateUserNoContent{}
}

/* ActivateUserNoContent describes a response with status code 204, with default header values.

No content is returned by this API endpoint
*/
type ActivateUserNoContent struct {
}

func (o *ActivateUserNoContent) Error() string {
	return fmt.Sprintf("[POST /v1/user/{id}/activate][%d] activateUserNoContent ", 204)
}

func (o *ActivateUserNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewActivateUserForbidden creates a ActivateUserForbidden with default headers values
func NewActivateUserForbidden() *ActivateUserForbidden {
	return &ActivateUserForbidden{}
}

/* ActivateUserForbidden describes a response with status code 403, with default header values.

Generic error message returned as a string
*/
type ActivateUserForbidden struct {
	Payload models.GenericError
}

func (o *ActivateUserForbidden) Error() string {
	return fmt.Sprintf("[POST /v1/user/{id}/activate][%d] activateUserForbidden  %+v", 403, o.Payload)
}
func (o *ActivateUserForbidden) GetPayload() models.GenericError {
	return o.Payload
}

func (o *ActivateUserForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewActivateUserInternalServerError creates a ActivateUserInternalServerError with default headers values
func NewActivateUserInternalServerError() *ActivateUserInternalServerError {
	return &ActivateUserInternalServerError{}
}

/* ActivateUserInternalServerError describes a response with status code 500, with default header values.

Generic error message returned as a string
*/
type ActivateUserInternalServerError struct {
	Payload models.GenericError
}

func (o *ActivateUserInternalServerError) Error() string {
	return fmt.Sprintf("[POST /v1/user/{id}/activate][%d] activateUserInternalServerError  %+v", 500, o.Payload)
}
func (o *ActivateUserInternalServerError) GetPayload() models.GenericError {
	return o.Payload
}

func (o *ActivateUserInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
