// Code generated by go-swagger; DO NOT EDIT.

package shorturl

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/turnkeyca/monolith/integration/models"
)

// GetShortURLReader is a Reader for the GetShortURL structure.
type GetShortURLReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetShortURLReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetShortURLOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewGetShortURLInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetShortURLOK creates a GetShortURLOK with default headers values
func NewGetShortURLOK() *GetShortURLOK {
	return &GetShortURLOK{}
}

/* GetShortURLOK describes a response with status code 200, with default header values.

A short url
*/
type GetShortURLOK struct {
	Payload *models.ShortURLDto
}

func (o *GetShortURLOK) Error() string {
	return fmt.Sprintf("[GET /v1/shorturl][%d] getShortUrlOK  %+v", 200, o.Payload)
}
func (o *GetShortURLOK) GetPayload() *models.ShortURLDto {
	return o.Payload
}

func (o *GetShortURLOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ShortURLDto)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetShortURLInternalServerError creates a GetShortURLInternalServerError with default headers values
func NewGetShortURLInternalServerError() *GetShortURLInternalServerError {
	return &GetShortURLInternalServerError{}
}

/* GetShortURLInternalServerError describes a response with status code 500, with default header values.

Generic error message returned as a string
*/
type GetShortURLInternalServerError struct {
	Payload models.GenericError
}

func (o *GetShortURLInternalServerError) Error() string {
	return fmt.Sprintf("[GET /v1/shorturl][%d] getShortUrlInternalServerError  %+v", 500, o.Payload)
}
func (o *GetShortURLInternalServerError) GetPayload() models.GenericError {
	return o.Payload
}

func (o *GetShortURLInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
