// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// EmploymentDto employment dto
//
// swagger:model EmploymentDto
type EmploymentDto struct {

	// additional details
	AdditionalDetails string `json:"additionalDetails,omitempty"`

	// annual salary
	AnnualSalary float64 `json:"annualSalary,omitempty"`

	// created on
	CreatedOn string `json:"createdOn,omitempty"`

	// duration
	Duration string `json:"duration,omitempty"`

	// employer
	Employer string `json:"employer,omitempty"`

	// Id
	ID string `json:"id,omitempty"`

	// last updated
	LastUpdated string `json:"lastUpdated,omitempty"`

	// occupation
	Occupation string `json:"occupation,omitempty"`

	// rent affordability
	RentAffordability string `json:"rentAffordability,omitempty"`

	// user Id
	UserID string `json:"userId,omitempty"`
}

// Validate validates this employment dto
func (m *EmploymentDto) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this employment dto based on context it is used
func (m *EmploymentDto) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *EmploymentDto) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EmploymentDto) UnmarshalBinary(b []byte) error {
	var res EmploymentDto
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
