// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// GenericError GenericError GenericError GenericError GenericError generic error
//
// swagger:model GenericError
type GenericError string

// Validate validates this generic error
func (m GenericError) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this generic error based on context it is used
func (m GenericError) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
