// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PetDto PetDto PetDto PetDto PetDto pet dto
//
// swagger:model PetDto
type PetDto struct {

	// breed
	Breed string `json:"breed,omitempty"`

	// created on
	CreatedOn string `json:"createdOn,omitempty"`

	// Id
	ID string `json:"id,omitempty"`

	// last updated
	LastUpdated string `json:"lastUpdated,omitempty"`

	// pet type
	PetType string `json:"petType,omitempty"`

	// size type
	SizeType string `json:"sizeType,omitempty"`

	// user Id
	UserID string `json:"userId,omitempty"`
}

// Validate validates this pet dto
func (m *PetDto) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this pet dto based on context it is used
func (m *PetDto) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PetDto) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PetDto) UnmarshalBinary(b []byte) error {
	var res PetDto
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
