// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RegisterTokenDto RegisterTokenDto RegisterTokenDto register token dto
//
// swagger:model RegisterTokenDto
type RegisterTokenDto struct {

	// is new user
	IsNewUser bool `json:"newUser,omitempty"`

	// login Id
	LoginID string `json:"id,omitempty"`

	// secret
	Secret string `json:"secret,omitempty"`
}

// Validate validates this register token dto
func (m *RegisterTokenDto) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this register token dto based on context it is used
func (m *RegisterTokenDto) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RegisterTokenDto) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RegisterTokenDto) UnmarshalBinary(b []byte) error {
	var res RegisterTokenDto
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
