// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ShortURLDto short Url dto
//
// swagger:model ShortUrlDto
type ShortURLDto struct {

	// Url
	URL string `json:"url,omitempty"`
}

// Validate validates this short Url dto
func (m *ShortURLDto) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this short Url dto based on context it is used
func (m *ShortURLDto) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ShortURLDto) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ShortURLDto) UnmarshalBinary(b []byte) error {
	var res ShortURLDto
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
