// Code generated by go-swagger; DO NOT EDIT.

package permission

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/turnkeyca/monolith/integration/models"
)

// AcceptPermissionReader is a Reader for the AcceptPermission structure.
type AcceptPermissionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AcceptPermissionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewAcceptPermissionNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewAcceptPermissionInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewAcceptPermissionNoContent creates a AcceptPermissionNoContent with default headers values
func NewAcceptPermissionNoContent() *AcceptPermissionNoContent {
	return &AcceptPermissionNoContent{}
}

/* AcceptPermissionNoContent describes a response with status code 204, with default header values.

No content is returned by this API endpoint
*/
type AcceptPermissionNoContent struct {
}

func (o *AcceptPermissionNoContent) Error() string {
	return fmt.Sprintf("[POST /v1/permission/{id}/accept][%d] acceptPermissionNoContent ", 204)
}

func (o *AcceptPermissionNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAcceptPermissionInternalServerError creates a AcceptPermissionInternalServerError with default headers values
func NewAcceptPermissionInternalServerError() *AcceptPermissionInternalServerError {
	return &AcceptPermissionInternalServerError{}
}

/* AcceptPermissionInternalServerError describes a response with status code 500, with default header values.

Generic error message returned as a string
*/
type AcceptPermissionInternalServerError struct {
	Payload models.GenericError
}

func (o *AcceptPermissionInternalServerError) Error() string {
	return fmt.Sprintf("[POST /v1/permission/{id}/accept][%d] acceptPermissionInternalServerError  %+v", 500, o.Payload)
}
func (o *AcceptPermissionInternalServerError) GetPayload() models.GenericError {
	return o.Payload
}

func (o *AcceptPermissionInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
