// Code generated by go-swagger; DO NOT EDIT.

package permission

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewAcceptPermissionParams creates a new AcceptPermissionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAcceptPermissionParams() *AcceptPermissionParams {
	return &AcceptPermissionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAcceptPermissionParamsWithTimeout creates a new AcceptPermissionParams object
// with the ability to set a timeout on a request.
func NewAcceptPermissionParamsWithTimeout(timeout time.Duration) *AcceptPermissionParams {
	return &AcceptPermissionParams{
		timeout: timeout,
	}
}

// NewAcceptPermissionParamsWithContext creates a new AcceptPermissionParams object
// with the ability to set a context for a request.
func NewAcceptPermissionParamsWithContext(ctx context.Context) *AcceptPermissionParams {
	return &AcceptPermissionParams{
		Context: ctx,
	}
}

// NewAcceptPermissionParamsWithHTTPClient creates a new AcceptPermissionParams object
// with the ability to set a custom HTTPClient for a request.
func NewAcceptPermissionParamsWithHTTPClient(client *http.Client) *AcceptPermissionParams {
	return &AcceptPermissionParams{
		HTTPClient: client,
	}
}

/* AcceptPermissionParams contains all the parameters to send to the API endpoint
   for the accept permission operation.

   Typically these are written to a http.Request.
*/
type AcceptPermissionParams struct {

	// Token.
	Token string

	/* ID.

	   The id of the permission for which the operation relates
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the accept permission params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AcceptPermissionParams) WithDefaults() *AcceptPermissionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the accept permission params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AcceptPermissionParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the accept permission params
func (o *AcceptPermissionParams) WithTimeout(timeout time.Duration) *AcceptPermissionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the accept permission params
func (o *AcceptPermissionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the accept permission params
func (o *AcceptPermissionParams) WithContext(ctx context.Context) *AcceptPermissionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the accept permission params
func (o *AcceptPermissionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the accept permission params
func (o *AcceptPermissionParams) WithHTTPClient(client *http.Client) *AcceptPermissionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the accept permission params
func (o *AcceptPermissionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithToken adds the token to the accept permission params
func (o *AcceptPermissionParams) WithToken(token string) *AcceptPermissionParams {
	o.SetToken(token)
	return o
}

// SetToken adds the token to the accept permission params
func (o *AcceptPermissionParams) SetToken(token string) {
	o.Token = token
}

// WithID adds the id to the accept permission params
func (o *AcceptPermissionParams) WithID(id string) *AcceptPermissionParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the accept permission params
func (o *AcceptPermissionParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *AcceptPermissionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Token
	if err := r.SetHeaderParam("Token", o.Token); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
