// Code generated by go-swagger; DO NOT EDIT.

package permission

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/turnkeyca/monolith/integration/models"
)

// CreatePermissionReader is a Reader for the CreatePermission structure.
type CreatePermissionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreatePermissionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewCreatePermissionNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreatePermissionBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewCreatePermissionForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewCreatePermissionUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCreatePermissionInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreatePermissionNoContent creates a CreatePermissionNoContent with default headers values
func NewCreatePermissionNoContent() *CreatePermissionNoContent {
	return &CreatePermissionNoContent{}
}

/* CreatePermissionNoContent describes a response with status code 204, with default header values.

No content is returned by this API endpoint
*/
type CreatePermissionNoContent struct {
}

func (o *CreatePermissionNoContent) Error() string {
	return fmt.Sprintf("[POST /v1/permission][%d] createPermissionNoContent ", 204)
}

func (o *CreatePermissionNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreatePermissionBadRequest creates a CreatePermissionBadRequest with default headers values
func NewCreatePermissionBadRequest() *CreatePermissionBadRequest {
	return &CreatePermissionBadRequest{}
}

/* CreatePermissionBadRequest describes a response with status code 400, with default header values.

Generic error message returned as a string
*/
type CreatePermissionBadRequest struct {
	Payload models.GenericError
}

func (o *CreatePermissionBadRequest) Error() string {
	return fmt.Sprintf("[POST /v1/permission][%d] createPermissionBadRequest  %+v", 400, o.Payload)
}
func (o *CreatePermissionBadRequest) GetPayload() models.GenericError {
	return o.Payload
}

func (o *CreatePermissionBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreatePermissionForbidden creates a CreatePermissionForbidden with default headers values
func NewCreatePermissionForbidden() *CreatePermissionForbidden {
	return &CreatePermissionForbidden{}
}

/* CreatePermissionForbidden describes a response with status code 403, with default header values.

Generic error message returned as a string
*/
type CreatePermissionForbidden struct {
	Payload models.GenericError
}

func (o *CreatePermissionForbidden) Error() string {
	return fmt.Sprintf("[POST /v1/permission][%d] createPermissionForbidden  %+v", 403, o.Payload)
}
func (o *CreatePermissionForbidden) GetPayload() models.GenericError {
	return o.Payload
}

func (o *CreatePermissionForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreatePermissionUnprocessableEntity creates a CreatePermissionUnprocessableEntity with default headers values
func NewCreatePermissionUnprocessableEntity() *CreatePermissionUnprocessableEntity {
	return &CreatePermissionUnprocessableEntity{}
}

/* CreatePermissionUnprocessableEntity describes a response with status code 422, with default header values.

Generic error message returned as a string
*/
type CreatePermissionUnprocessableEntity struct {
	Payload models.GenericError
}

func (o *CreatePermissionUnprocessableEntity) Error() string {
	return fmt.Sprintf("[POST /v1/permission][%d] createPermissionUnprocessableEntity  %+v", 422, o.Payload)
}
func (o *CreatePermissionUnprocessableEntity) GetPayload() models.GenericError {
	return o.Payload
}

func (o *CreatePermissionUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreatePermissionInternalServerError creates a CreatePermissionInternalServerError with default headers values
func NewCreatePermissionInternalServerError() *CreatePermissionInternalServerError {
	return &CreatePermissionInternalServerError{}
}

/* CreatePermissionInternalServerError describes a response with status code 500, with default header values.

Generic error message returned as a string
*/
type CreatePermissionInternalServerError struct {
	Payload models.GenericError
}

func (o *CreatePermissionInternalServerError) Error() string {
	return fmt.Sprintf("[POST /v1/permission][%d] createPermissionInternalServerError  %+v", 500, o.Payload)
}
func (o *CreatePermissionInternalServerError) GetPayload() models.GenericError {
	return o.Payload
}

func (o *CreatePermissionInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
