// Code generated by go-swagger; DO NOT EDIT.

package permission

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeletePermissionParams creates a new DeletePermissionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeletePermissionParams() *DeletePermissionParams {
	return &DeletePermissionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeletePermissionParamsWithTimeout creates a new DeletePermissionParams object
// with the ability to set a timeout on a request.
func NewDeletePermissionParamsWithTimeout(timeout time.Duration) *DeletePermissionParams {
	return &DeletePermissionParams{
		timeout: timeout,
	}
}

// NewDeletePermissionParamsWithContext creates a new DeletePermissionParams object
// with the ability to set a context for a request.
func NewDeletePermissionParamsWithContext(ctx context.Context) *DeletePermissionParams {
	return &DeletePermissionParams{
		Context: ctx,
	}
}

// NewDeletePermissionParamsWithHTTPClient creates a new DeletePermissionParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeletePermissionParamsWithHTTPClient(client *http.Client) *DeletePermissionParams {
	return &DeletePermissionParams{
		HTTPClient: client,
	}
}

/* DeletePermissionParams contains all the parameters to send to the API endpoint
   for the delete permission operation.

   Typically these are written to a http.Request.
*/
type DeletePermissionParams struct {

	// Token.
	Token string

	/* ID.

	   The id of the permission for which the operation relates
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete permission params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeletePermissionParams) WithDefaults() *DeletePermissionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete permission params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeletePermissionParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete permission params
func (o *DeletePermissionParams) WithTimeout(timeout time.Duration) *DeletePermissionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete permission params
func (o *DeletePermissionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete permission params
func (o *DeletePermissionParams) WithContext(ctx context.Context) *DeletePermissionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete permission params
func (o *DeletePermissionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete permission params
func (o *DeletePermissionParams) WithHTTPClient(client *http.Client) *DeletePermissionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete permission params
func (o *DeletePermissionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithToken adds the token to the delete permission params
func (o *DeletePermissionParams) WithToken(token string) *DeletePermissionParams {
	o.SetToken(token)
	return o
}

// SetToken adds the token to the delete permission params
func (o *DeletePermissionParams) SetToken(token string) {
	o.Token = token
}

// WithID adds the id to the delete permission params
func (o *DeletePermissionParams) WithID(id string) *DeletePermissionParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete permission params
func (o *DeletePermissionParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeletePermissionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Token
	if err := r.SetHeaderParam("Token", o.Token); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
