// Code generated by go-swagger; DO NOT EDIT.

package permission

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetPermissionsByUserIDParams creates a new GetPermissionsByUserIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetPermissionsByUserIDParams() *GetPermissionsByUserIDParams {
	return &GetPermissionsByUserIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetPermissionsByUserIDParamsWithTimeout creates a new GetPermissionsByUserIDParams object
// with the ability to set a timeout on a request.
func NewGetPermissionsByUserIDParamsWithTimeout(timeout time.Duration) *GetPermissionsByUserIDParams {
	return &GetPermissionsByUserIDParams{
		timeout: timeout,
	}
}

// NewGetPermissionsByUserIDParamsWithContext creates a new GetPermissionsByUserIDParams object
// with the ability to set a context for a request.
func NewGetPermissionsByUserIDParamsWithContext(ctx context.Context) *GetPermissionsByUserIDParams {
	return &GetPermissionsByUserIDParams{
		Context: ctx,
	}
}

// NewGetPermissionsByUserIDParamsWithHTTPClient creates a new GetPermissionsByUserIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetPermissionsByUserIDParamsWithHTTPClient(client *http.Client) *GetPermissionsByUserIDParams {
	return &GetPermissionsByUserIDParams{
		HTTPClient: client,
	}
}

/* GetPermissionsByUserIDParams contains all the parameters to send to the API endpoint
   for the get permissions by user Id operation.

   Typically these are written to a http.Request.
*/
type GetPermissionsByUserIDParams struct {

	// Token.
	Token string

	/* UserID.

	   The user id
	*/
	UserID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get permissions by user Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPermissionsByUserIDParams) WithDefaults() *GetPermissionsByUserIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get permissions by user Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPermissionsByUserIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get permissions by user Id params
func (o *GetPermissionsByUserIDParams) WithTimeout(timeout time.Duration) *GetPermissionsByUserIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get permissions by user Id params
func (o *GetPermissionsByUserIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get permissions by user Id params
func (o *GetPermissionsByUserIDParams) WithContext(ctx context.Context) *GetPermissionsByUserIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get permissions by user Id params
func (o *GetPermissionsByUserIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get permissions by user Id params
func (o *GetPermissionsByUserIDParams) WithHTTPClient(client *http.Client) *GetPermissionsByUserIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get permissions by user Id params
func (o *GetPermissionsByUserIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithToken adds the token to the get permissions by user Id params
func (o *GetPermissionsByUserIDParams) WithToken(token string) *GetPermissionsByUserIDParams {
	o.SetToken(token)
	return o
}

// SetToken adds the token to the get permissions by user Id params
func (o *GetPermissionsByUserIDParams) SetToken(token string) {
	o.Token = token
}

// WithUserID adds the userID to the get permissions by user Id params
func (o *GetPermissionsByUserIDParams) WithUserID(userID string) *GetPermissionsByUserIDParams {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the get permissions by user Id params
func (o *GetPermissionsByUserIDParams) SetUserID(userID string) {
	o.UserID = userID
}

// WriteToRequest writes these params to a swagger request
func (o *GetPermissionsByUserIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Token
	if err := r.SetHeaderParam("Token", o.Token); err != nil {
		return err
	}

	// query param userId
	qrUserID := o.UserId
	qUserID := qrUserID
	if qUserID != "" {

		if err := r.SetQueryParam("userId", qUserID); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
