// Code generated by go-swagger; DO NOT EDIT.

package permission

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/turnkeyca/monolith/integration/models"
)

// GetPermissionsByUserIDReader is a Reader for the GetPermissionsByUserID structure.
type GetPermissionsByUserIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPermissionsByUserIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetPermissionsByUserIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewGetPermissionsByUserIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetPermissionsByUserIDOK creates a GetPermissionsByUserIDOK with default headers values
func NewGetPermissionsByUserIDOK() *GetPermissionsByUserIDOK {
	return &GetPermissionsByUserIDOK{}
}

/* GetPermissionsByUserIDOK describes a response with status code 200, with default header values.

A list of permissions
*/
type GetPermissionsByUserIDOK struct {
	Payload []*models.PermissionDto
}

func (o *GetPermissionsByUserIDOK) Error() string {
	return fmt.Sprintf("[GET /v1/permission][%d] getPermissionsByUserIdOK  %+v", 200, o.Payload)
}
func (o *GetPermissionsByUserIDOK) GetPayload() []*models.PermissionDto {
	return o.Payload
}

func (o *GetPermissionsByUserIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetPermissionsByUserIDInternalServerError creates a GetPermissionsByUserIDInternalServerError with default headers values
func NewGetPermissionsByUserIDInternalServerError() *GetPermissionsByUserIDInternalServerError {
	return &GetPermissionsByUserIDInternalServerError{}
}

/* GetPermissionsByUserIDInternalServerError describes a response with status code 500, with default header values.

Generic error message returned as a string
*/
type GetPermissionsByUserIDInternalServerError struct {
	Payload models.GenericError
}

func (o *GetPermissionsByUserIDInternalServerError) Error() string {
	return fmt.Sprintf("[GET /v1/permission][%d] getPermissionsByUserIdInternalServerError  %+v", 500, o.Payload)
}
func (o *GetPermissionsByUserIDInternalServerError) GetPayload() models.GenericError {
	return o.Payload
}

func (o *GetPermissionsByUserIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
