// Code generated by go-swagger; DO NOT EDIT.

package pet

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetPetParams creates a new GetPetParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetPetParams() *GetPetParams {
	return &GetPetParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetPetParamsWithTimeout creates a new GetPetParams object
// with the ability to set a timeout on a request.
func NewGetPetParamsWithTimeout(timeout time.Duration) *GetPetParams {
	return &GetPetParams{
		timeout: timeout,
	}
}

// NewGetPetParamsWithContext creates a new GetPetParams object
// with the ability to set a context for a request.
func NewGetPetParamsWithContext(ctx context.Context) *GetPetParams {
	return &GetPetParams{
		Context: ctx,
	}
}

// NewGetPetParamsWithHTTPClient creates a new GetPetParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetPetParamsWithHTTPClient(client *http.Client) *GetPetParams {
	return &GetPetParams{
		HTTPClient: client,
	}
}

/* GetPetParams contains all the parameters to send to the API endpoint
   for the get pet operation.

   Typically these are written to a http.Request.
*/
type GetPetParams struct {

	// Token.
	Token string

	/* ID.

	   The id of the pet for which the operation relates
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get pet params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPetParams) WithDefaults() *GetPetParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get pet params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPetParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get pet params
func (o *GetPetParams) WithTimeout(timeout time.Duration) *GetPetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get pet params
func (o *GetPetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get pet params
func (o *GetPetParams) WithContext(ctx context.Context) *GetPetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get pet params
func (o *GetPetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get pet params
func (o *GetPetParams) WithHTTPClient(client *http.Client) *GetPetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get pet params
func (o *GetPetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithToken adds the token to the get pet params
func (o *GetPetParams) WithToken(token string) *GetPetParams {
	o.SetToken(token)
	return o
}

// SetToken adds the token to the get pet params
func (o *GetPetParams) SetToken(token string) {
	o.Token = token
}

// WithID adds the id to the get pet params
func (o *GetPetParams) WithID(id string) *GetPetParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get pet params
func (o *GetPetParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetPetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Token
	if err := r.SetHeaderParam("Token", o.Token); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
