// Code generated by go-swagger; DO NOT EDIT.

package pet

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/turnkeyca/monolith/integration/models"
)

// GetPetReader is a Reader for the GetPet structure.
type GetPetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetPetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewGetPetForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetPetNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetPetInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetPetOK creates a GetPetOK with default headers values
func NewGetPetOK() *GetPetOK {
	return &GetPetOK{}
}

/* GetPetOK describes a response with status code 200, with default header values.

A pet
*/
type GetPetOK struct {
	Payload *models.PetDto
}

func (o *GetPetOK) Error() string {
	return fmt.Sprintf("[GET /v1/pet/{id}][%d] getPetOK  %+v", 200, o.Payload)
}
func (o *GetPetOK) GetPayload() *models.PetDto {
	return o.Payload
}

func (o *GetPetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PetDto)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetPetForbidden creates a GetPetForbidden with default headers values
func NewGetPetForbidden() *GetPetForbidden {
	return &GetPetForbidden{}
}

/* GetPetForbidden describes a response with status code 403, with default header values.

Generic error message returned as a string
*/
type GetPetForbidden struct {
	Payload models.GenericError
}

func (o *GetPetForbidden) Error() string {
	return fmt.Sprintf("[GET /v1/pet/{id}][%d] getPetForbidden  %+v", 403, o.Payload)
}
func (o *GetPetForbidden) GetPayload() models.GenericError {
	return o.Payload
}

func (o *GetPetForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetPetNotFound creates a GetPetNotFound with default headers values
func NewGetPetNotFound() *GetPetNotFound {
	return &GetPetNotFound{}
}

/* GetPetNotFound describes a response with status code 404, with default header values.

Generic error message returned as a string
*/
type GetPetNotFound struct {
	Payload models.GenericError
}

func (o *GetPetNotFound) Error() string {
	return fmt.Sprintf("[GET /v1/pet/{id}][%d] getPetNotFound  %+v", 404, o.Payload)
}
func (o *GetPetNotFound) GetPayload() models.GenericError {
	return o.Payload
}

func (o *GetPetNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetPetInternalServerError creates a GetPetInternalServerError with default headers values
func NewGetPetInternalServerError() *GetPetInternalServerError {
	return &GetPetInternalServerError{}
}

/* GetPetInternalServerError describes a response with status code 500, with default header values.

Generic error message returned as a string
*/
type GetPetInternalServerError struct {
	Payload models.GenericError
}

func (o *GetPetInternalServerError) Error() string {
	return fmt.Sprintf("[GET /v1/pet/{id}][%d] getPetInternalServerError  %+v", 500, o.Payload)
}
func (o *GetPetInternalServerError) GetPayload() models.GenericError {
	return o.Payload
}

func (o *GetPetInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
