// Code generated by go-swagger; DO NOT EDIT.

package pet

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetPetsByUserIDParams creates a new GetPetsByUserIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetPetsByUserIDParams() *GetPetsByUserIDParams {
	return &GetPetsByUserIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetPetsByUserIDParamsWithTimeout creates a new GetPetsByUserIDParams object
// with the ability to set a timeout on a request.
func NewGetPetsByUserIDParamsWithTimeout(timeout time.Duration) *GetPetsByUserIDParams {
	return &GetPetsByUserIDParams{
		timeout: timeout,
	}
}

// NewGetPetsByUserIDParamsWithContext creates a new GetPetsByUserIDParams object
// with the ability to set a context for a request.
func NewGetPetsByUserIDParamsWithContext(ctx context.Context) *GetPetsByUserIDParams {
	return &GetPetsByUserIDParams{
		Context: ctx,
	}
}

// NewGetPetsByUserIDParamsWithHTTPClient creates a new GetPetsByUserIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetPetsByUserIDParamsWithHTTPClient(client *http.Client) *GetPetsByUserIDParams {
	return &GetPetsByUserIDParams{
		HTTPClient: client,
	}
}

/* GetPetsByUserIDParams contains all the parameters to send to the API endpoint
   for the get pets by user Id operation.

   Typically these are written to a http.Request.
*/
type GetPetsByUserIDParams struct {

	// Token.
	Token string

	/* UserID.

	   The user id
	*/
	UserID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get pets by user Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPetsByUserIDParams) WithDefaults() *GetPetsByUserIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get pets by user Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPetsByUserIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get pets by user Id params
func (o *GetPetsByUserIDParams) WithTimeout(timeout time.Duration) *GetPetsByUserIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get pets by user Id params
func (o *GetPetsByUserIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get pets by user Id params
func (o *GetPetsByUserIDParams) WithContext(ctx context.Context) *GetPetsByUserIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get pets by user Id params
func (o *GetPetsByUserIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get pets by user Id params
func (o *GetPetsByUserIDParams) WithHTTPClient(client *http.Client) *GetPetsByUserIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get pets by user Id params
func (o *GetPetsByUserIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithToken adds the token to the get pets by user Id params
func (o *GetPetsByUserIDParams) WithToken(token string) *GetPetsByUserIDParams {
	o.SetToken(token)
	return o
}

// SetToken adds the token to the get pets by user Id params
func (o *GetPetsByUserIDParams) SetToken(token string) {
	o.Token = token
}

// WithUserID adds the userID to the get pets by user Id params
func (o *GetPetsByUserIDParams) WithUserID(userID string) *GetPetsByUserIDParams {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the get pets by user Id params
func (o *GetPetsByUserIDParams) SetUserID(userID string) {
	o.UserID = userID
}

// WriteToRequest writes these params to a swagger request
func (o *GetPetsByUserIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Token
	if err := r.SetHeaderParam("Token", o.Token); err != nil {
		return err
	}

	// query param userId
	qrUserID := o.UserID
	qUserID := qrUserID
	if qUserID != "" {

		if err := r.SetQueryParam("userId", qUserID); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
