// Code generated by go-swagger; DO NOT EDIT.

package pet

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/turnkeyca/monolith/integration/models"
)

// UpdatePetReader is a Reader for the UpdatePet structure.
type UpdatePetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdatePetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewUpdatePetNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewUpdatePetBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewUpdatePetForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewUpdatePetNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewUpdatePetUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewUpdatePetInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewUpdatePetNoContent creates a UpdatePetNoContent with default headers values
func NewUpdatePetNoContent() *UpdatePetNoContent {
	return &UpdatePetNoContent{}
}

/* UpdatePetNoContent describes a response with status code 204, with default header values.

No content is returned by this API endpoint
*/
type UpdatePetNoContent struct {
}

func (o *UpdatePetNoContent) Error() string {
	return fmt.Sprintf("[PUT /v1/pet/{id}][%d] updatePetNoContent ", 204)
}

func (o *UpdatePetNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdatePetBadRequest creates a UpdatePetBadRequest with default headers values
func NewUpdatePetBadRequest() *UpdatePetBadRequest {
	return &UpdatePetBadRequest{}
}

/* UpdatePetBadRequest describes a response with status code 400, with default header values.

Generic error message returned as a string
*/
type UpdatePetBadRequest struct {
	Payload models.GenericError
}

func (o *UpdatePetBadRequest) Error() string {
	return fmt.Sprintf("[PUT /v1/pet/{id}][%d] updatePetBadRequest  %+v", 400, o.Payload)
}
func (o *UpdatePetBadRequest) GetPayload() models.GenericError {
	return o.Payload
}

func (o *UpdatePetBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdatePetForbidden creates a UpdatePetForbidden with default headers values
func NewUpdatePetForbidden() *UpdatePetForbidden {
	return &UpdatePetForbidden{}
}

/* UpdatePetForbidden describes a response with status code 403, with default header values.

Generic error message returned as a string
*/
type UpdatePetForbidden struct {
	Payload models.GenericError
}

func (o *UpdatePetForbidden) Error() string {
	return fmt.Sprintf("[PUT /v1/pet/{id}][%d] updatePetForbidden  %+v", 403, o.Payload)
}
func (o *UpdatePetForbidden) GetPayload() models.GenericError {
	return o.Payload
}

func (o *UpdatePetForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdatePetNotFound creates a UpdatePetNotFound with default headers values
func NewUpdatePetNotFound() *UpdatePetNotFound {
	return &UpdatePetNotFound{}
}

/* UpdatePetNotFound describes a response with status code 404, with default header values.

Generic error message returned as a string
*/
type UpdatePetNotFound struct {
	Payload models.GenericError
}

func (o *UpdatePetNotFound) Error() string {
	return fmt.Sprintf("[PUT /v1/pet/{id}][%d] updatePetNotFound  %+v", 404, o.Payload)
}
func (o *UpdatePetNotFound) GetPayload() models.GenericError {
	return o.Payload
}

func (o *UpdatePetNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdatePetUnprocessableEntity creates a UpdatePetUnprocessableEntity with default headers values
func NewUpdatePetUnprocessableEntity() *UpdatePetUnprocessableEntity {
	return &UpdatePetUnprocessableEntity{}
}

/* UpdatePetUnprocessableEntity describes a response with status code 422, with default header values.

Generic error message returned as a string
*/
type UpdatePetUnprocessableEntity struct {
	Payload models.GenericError
}

func (o *UpdatePetUnprocessableEntity) Error() string {
	return fmt.Sprintf("[PUT /v1/pet/{id}][%d] updatePetUnprocessableEntity  %+v", 422, o.Payload)
}
func (o *UpdatePetUnprocessableEntity) GetPayload() models.GenericError {
	return o.Payload
}

func (o *UpdatePetUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdatePetInternalServerError creates a UpdatePetInternalServerError with default headers values
func NewUpdatePetInternalServerError() *UpdatePetInternalServerError {
	return &UpdatePetInternalServerError{}
}

/* UpdatePetInternalServerError describes a response with status code 500, with default header values.

Generic error message returned as a string
*/
type UpdatePetInternalServerError struct {
	Payload models.GenericError
}

func (o *UpdatePetInternalServerError) Error() string {
	return fmt.Sprintf("[PUT /v1/pet/{id}][%d] updatePetInternalServerError  %+v", 500, o.Payload)
}
func (o *UpdatePetInternalServerError) GetPayload() models.GenericError {
	return o.Payload
}

func (o *UpdatePetInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
